### ISSUE TITLE
Error with classes.txt file

### ISSUE THREAD

**Issue by Ram-Godavarthi** [hai-h-nguyen/Yolo2Pascal-annotation-conversion#3]
HI,

I tried to convert yolo format to pascal format

I haev folder with images and .txt files

:txt file consist of : classID x y width height

I do not have classes.txt file with me..

what is that fiel for?

How it looks like?

Any help to create it manually.

Thanks in advance

**Comment by hai-h-nguyen** [comment]
Hi, I don't remember the format for this file but it is autonomously created when using LabelImage to label your dataset. So I suggest using that tool to have a look how to create it manually. It should be simple I guess. 
https://github.com/tzutalin/labelImg
In that repo, there is an example as well
https://github.com/tzutalin/labelImg/blob/master/data/predefined_classes.txt

**Comment by Farjad3253** [comment]
@Ram-Godavarthi  The classes.txt file is a simple text file that contains the label for your classes. If you have two classes like cat and dog then write cat and dog in alphabetical order in a text file and save it. Do like this and I hope it will resolve your issue. Waiting for your code execution.
