### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by vim5818** [hai-h-nguyen/Yolo2Pascal-annotation-conversion#4]
I followed the procedure. 

used the following command

```
*python yolo2voc.py C:/Users/VVSB/Desktop/FLIR_Dataset/FLIR_ADAS_1_3/New folder/image C:/Users/VVSB/Desktop/FLIR_Dataset/FLIR_ADAS_1_3/New folder/Image/text
```

There is no Output. 
python3 gives some error. 

Thank you for support

**Comment by hai-h-nguyen** [comment]
What is the error you get with python3?

**Comment by hai-h-nguyen** [comment]
I update the repo with demo images. You should be able to run it yourself. Let me know if you still have an issue.
